### ISSUE TITLE
Enhancement: Push simple HTML data types

### ISSUE THREAD

**Issue by ionas** [alt3/cakephp-validation-exposer#7]
Push simple (HTML5) data types:
- string
- email
- password
- range
- date
- time
- datetime
- boolean/flag (checkbox)

This should allow most frontend frameworks like ReactJS, Framework7, Ionic, Foundation, Bootstrap, Angular, etc, to render the correct widgets.

Now sure how to push complex type information like associations, enums. Enums would be possible via inList validation rule. But how do you push along association options? A url to query via JSON? A static list (say you want to create a product and assign a manufacturer, or want to create a post and assign tags)?

**Comment by bravo-kernel** [comment]
First of all, I would like this plugin to be as micro as possible, with as little magic as possible. Basically because there are probably a million solutions/directions thinkable. Simply take the validation rules produced by ValidationExposer and transform them as you see fit (outside of the plugin).

For instance, my app Tables use custom validation messages, where my Icu library creates (json encoded) rich messages using **a personal variation of the [ICU-format](http://userguide.icu-project.org/formatparse/messages)**.

``` php
        $validator
            ->requirePresence('password', 'create')
            ->notEmpty('password')
            ->add('password', [
                'MIN_LENGTH' => [
                    'rule' => ['minLength', Configure::readOrFail('Api.password.min_length')],
                    'message' => Icu::message('Your password must be at least {minLength} characters.', [
                        'minLength' => Configure::readOrFail('Api.password.min_length')
                    ])
                ],
                'MAX_LENGTH' => [
                    'rule' => ['maxLength', Configure::readOrFail('Api.password.max_length')],
                    'message' => Icu::message('Your password cannot exceed {maxLength} characters.', [
                        'maxLength' => Configure::readOrFail('Api.password.max_length')
                    ])
                ],
```

These Icu library created messages are then decoded by a custom validation ExceptionRenderer so I can respond like this:

``` json
{
  "success": false,
  "data": {
    "code": 422,
    "url": "/users/register",
    "message": "Validation errors occured",
    "errorCount": 2,
    "errors": [
      {
        "fields": [
          "email"
        ],
        "rule": "FORMAT",
        "suggestedMessage": "Invalid email address format."
      },
      {
        "fields": [
          "password"
        ],
        "rule": "MIN_UPPERCASES",
        "suggestedMessage": "Your password must contain at least {minUcases} uppercase characters.",
        "messageArguments": {
          "minUcases": 1
        }
      }
    ]
  }
}
```

As you can see these validation responses now use a totally different structure than the default Cake/CRUD ones. Main benefit, suggestedMessage make the response understandable for the frontend dev, arguments can be hooked/coded into the [react-intl]() translations the frontend uses.

All very well  but these are just the 412 responses the api backend responds with when passed data is invalid and that's exactly why I made this plugin. ValidationExposer gives me all validation information, I then use my magic to enrich as I see fit. In my case the react frontend now has and can use the same validation logic as my api.

**Now for your suggestion;** I have deliberately not chosen not include typing but could easily provide (html5 or any other) types to the frontend by using ICU inspired argument parameters similar to below:

```
Your password must contain at least {minUcases, integer} uppercase characters.
Today's date {dateToday, data} is quite awesome.
```

Closing for now
